# Generated by Django 5.2.6 on 2025-09-08 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPartner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('center_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Center / Location')),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimated Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Training Partner',
                'verbose_name_plural': 'Training Partners',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('theme', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SMMU', 'Pending SMMU Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL)),
                ('beneficiaries', models.ManyToManyField(blank=True, related_name='batches', to='bmmu.beneficiary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('trainers', models.ManyToManyField(blank=True, related_name='batches', to='bmmu.mastertrainer')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='bmmu.trainingplan')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='bmmu.trainingpartner')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
