# Generated by Django 5.2.6 on 2025-09-09 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0003_alter_batch_options_remove_batch_approval_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='theme_expert',
            field=models.ForeignKey(blank=True, help_text='SMMU user who is theme expert (nullable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_expert_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='theme_expert_contact',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Theme Expert Contact No.'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='training_partner',
            field=models.ForeignKey(blank=True, help_text='Preferred / assigned training partner (nullable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans', to='bmmu.trainingpartner'),
        ),
    ]
