# Generated by Django 5.2.6 on 2025-09-09 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0004_trainingplan_theme_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpartner',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='certifications',
            field=models.FileField(blank=True, null=True, upload_to='partner_certs/'),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='partner_pfps/'),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_partner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('bmmu', 'BMMU'), ('dmmu', 'DMMU'), ('smmu', 'SMMU'), ('training_partner', 'Training Partner'), ('admin', 'Admin')], default='bmmu', max_length=20),
        ),
    ]
