# Generated by Django 5.2.6 on 2025-09-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0005_trainingpartner_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPartnerAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(help_text='Theme name (text)', max_length=255)),
                ('block', models.CharField(help_text='Block name / identifier', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bmmu.trainingpartner')),
            ],
            options={
                'verbose_name': 'Training Partner Assignment',
                'verbose_name_plural': 'Training Partner Assignments',
                'unique_together': {('theme', 'block')},
            },
        ),
    ]
