# Generated by Django 5.2.6 on 2025-09-09 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0006_trainingpartnerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertrainer',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills/themes/modules (used to match trainers to training plans).', null=True),
        ),
        migrations.CreateModel(
            name='MasterTrainerExpertise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proficiency', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recommended', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='bmmu.mastertrainer')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_trainers', to='bmmu.trainingplan')),
            ],
            options={
                'verbose_name': 'Master Trainer Expertise',
                'verbose_name_plural': 'Master Trainer Expertises',
                'unique_together': {('trainer', 'training_plan')},
            },
        ),
    ]
