# Generated by Django 5.2.6 on 2025-09-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0007_mastertrainer_skills_mastertrainerexpertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='centre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Centre (confirmed)'),
        ),
        migrations.AddField(
            model_name='batch',
            name='centre_proposed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Centre (proposed by partner)'),
        ),
    ]
