# Generated by Django 5.2.6 on 2025-09-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0008_batch_centre_batch_centre_proposed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpartner',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='IFSC / Routing'),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='mou_form',
            field=models.FileField(blank=True, null=True, upload_to='partner_mous/', verbose_name='Signed MoU (PDF)'),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='tpm_registration_no',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Registration No (TPM/Org)'),
        ),
    ]
