# Generated by Django 5.2.6 on 2025-09-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0009_trainingpartner_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='approval_status',
            field=models.CharField(blank=True, help_text="Maps Excel 'Approval' column (Approved / Pending / Rejected / notes).", max_length=150, null=True, verbose_name='Approval status / notes'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='batch_creation_ekyc',
            field=models.CharField(blank=True, help_text="Maps Excel 'Batch Creation/eKYC' values (Yes/No/notes).", max_length=150, null=True, verbose_name='Batch Creation / eKYC'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='participant_selection',
            field=models.TextField(blank=True, help_text="Free-text notes from Excel 'Participant selection' column.", null=True, verbose_name='Participant selection (notes)'),
        ),
    ]
