# Generated by Django 5.2.6 on 2025-09-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0010_trainingplan_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertrainer',
            name='aadhaar_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Aadhaar No'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Branch Name'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='certificates',
            field=models.CharField(blank=True, help_text='Optional: certificate filenames or notes from Excel.', max_length=512, null=True, verbose_name='Certificates (notes/filename)'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='empanel_district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Empanel District'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='ifsc',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='IFSC'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='mobile_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Mobile No.'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='modules_assigned',
            field=models.TextField(blank=True, help_text="Comma-separated list from 'Modules(Training Name)' Excel column.", null=True, verbose_name='Modules / Trainings assigned'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='parent_or_spouse_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Father/Mother/Spouse Name'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_pfps/'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='social_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Social Category'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='trainings_assigned',
            field=models.TextField(blank=True, null=True, verbose_name='Trainings Assigned'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='trainings_running',
            field=models.TextField(blank=True, null=True, verbose_name='Trainings Running'),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='skills',
            field=models.TextField(blank=True, help_text="Comma-separated skills/modules. (Maps Excel 'Thematic Sector' column.)", null=True),
        ),
    ]
