# Generated by Django 5.2.6 on 2025-09-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0012_mastertrainercertificate_trainingpartnersubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='participant_selection',
            field=models.CharField(blank=True, choices=[('BMMU', 'BMMU'), ('DMMU', 'DMMU'), ('SMMU', 'SMMU')], max_length=20, null=True, verbose_name='Participant Selection Authority'),
        ),
    ]
