# Generated by Django 5.2.6 on 2025-09-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0013_alter_trainingplan_participant_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='level_of_training',
            field=models.CharField(blank=True, choices=[('VILLAGE', 'Village'), ('SHG', 'SHG'), ('CLF', 'CLF'), ('BLOCK', 'Block'), ('BLOCK/DISTRICT', 'Block/District'), ('CMTC /BLOCK', 'CMTC/Block'), ('DISTRICT', 'District'), ('STATE', 'State'), ('OUTSIDE STATE', 'Outside State')], max_length=20, null=True, verbose_name='Level of training'),
        ),
    ]
