# Generated by Django 5.2.6 on 2025-09-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0015_alter_trainingplan_level_of_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='type_of_training',
            field=models.CharField(choices=[('RES', 'Residential'), ('NON RES', 'Non-residential'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Type of Training'),
        ),
    ]
