# Generated by Django 5.2.6 on 2025-09-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0018_create_through_and_new_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='beneficiaries_v2',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='trainers_v2',
        ),
    ]
