# Generated by Django 5.2.6 on 2025-09-12 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertrainer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional link to User account for self-service login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
