# Generated by Django 5.2.6 on 2025-09-26 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0002_mastertrainer_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trainingpartner',
            name='bmmu_traini_center__901c3c_idx',
        ),
        migrations.RenameField(
            model_name='beneficiarybatchregistration',
            old_name='created_at',
            new_name='registered_on',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='bank_loan_status',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='member_lokos_code',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='shg_lokos_code',
        ),
        migrations.RemoveField(
            model_name='beneficiarybatchregistration',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='beneficiarybatchregistration',
            name='certificate_issued',
        ),
        migrations.RemoveField(
            model_name='beneficiarybatchregistration',
            name='ekyc_registered_on',
        ),
        migrations.RemoveField(
            model_name='beneficiarybatchregistration',
            name='registered_on_start',
        ),
        migrations.RemoveField(
            model_name='themeexpertassignment',
            name='expert_contact',
        ),
        migrations.RemoveField(
            model_name='trainingpartner',
            name='signed_report_upload_status',
        ),
        migrations.RemoveField(
            model_name='trainingpartner',
            name='signed_report_uploaded_by',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='participant_selection',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='training_partner',
        ),
        migrations.AddField(
            model_name='batch',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='batches', to='bmmu.trainingpartnersubmission'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='aadhar_kyc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Aadhar KYC'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='account_opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='account_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='approval_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='benef_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Beneficiary Status'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='date_of_approval',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='date_of_formation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='date_of_joining_shg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='disability',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Disability'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='disability_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Disability Type'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='ebk_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='eBK ID'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='ebk_mobile_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='eBK Mobile No.'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='ebk_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='eBK Name'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='ekyc_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ekyc status'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inactive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='inactive_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='insurance_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Insurance Status'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='is_head_of_family',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='HOF'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='member_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Member Code'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='member_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Migrated/Lokos'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='nrega_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NREGA Job Card No'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='nrlm_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NRLM MIS ID'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='pmay_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='PMAY-G ID'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='primary_livelihood',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primary Livelihood'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='pvtg_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PVTG Category'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='relation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Relation for name'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Religion'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='secc_tin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='SECC TIN'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='secondary_livelihood',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Secondary Livelihood'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='shg_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='SHG Code'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='state_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='STATE MIS ID'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='tertiary_livelihood',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tertiary Livelihood'),
        ),
        migrations.AddField(
            model_name='beneficiarybatchregistration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='designation',
            field=models.CharField(blank=True, choices=[('DRP', 'DRP'), ('SRP', 'SRP')], db_index=True, max_length=3, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='beneficiarybatchregistration',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_registrations', to='bmmu.batch'),
        ),
        migrations.AlterField(
            model_name='beneficiarybatchregistration',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='bmmu.beneficiary'),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='any_other_tots',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='other_achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='recommended_tots_by_dmmu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Skills / Thematic Sectors'),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='success_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='success_story_publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='thematic_expert_recommendation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainingpartner',
            name='center_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainingpartner',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingpartner',
            name='photographs_submission',
            field=models.TextField(blank=True, help_text='Summary / meta about photographs', null=True),
        ),
        migrations.AlterField(
            model_name='trainingpartner',
            name='signed_report_file',
            field=models.FileField(blank=True, null=True, upload_to='partner_signed_reports/'),
        ),
        migrations.AlterField(
            model_name='trainingpartner',
            name='targets_allocated',
            field=models.TextField(blank=True, help_text='Optional summary of targets allocated', null=True),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='level_of_training',
            field=models.CharField(blank=True, choices=[('VILLAGE', 'Village'), ('SHG', 'SHG'), ('CLF', 'CLF'), ('BLOCK', 'Block'), ('BLOCK_DISTRICT', 'Block/District'), ('CMTC_BLOCK', 'CMTC/Block'), ('DISTRICT', 'District'), ('STATE', 'State'), ('WITHIN_STATE', 'Within State'), ('OUTSIDE_STATE', 'Outside State')], max_length=32, null=True, verbose_name='Level of training'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='theme_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_training_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='type_of_training',
            field=models.CharField(choices=[('RES', 'Residential'), ('NON_RES', 'Non-residential'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Type of Training'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('bmmu', 'BMMU'), ('dmmu', 'DMMU'), ('smmu', 'SMMU'), ('training_partner', 'Training Partner'), ('master_trainer', 'Master Trainer'), ('admin', 'Admin')], default='bmmu', max_length=32),
        ),
        migrations.AddIndex(
            model_name='mastertrainer',
            index=models.Index(fields=['designation'], name='bmmu_master_designa_f02268_idx'),
        ),
        migrations.DeleteModel(
            name='EkycVerification',
        ),
    ]
