# Generated by Django 5.2.6 on 2025-09-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0004_alter_trainingplan_type_of_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='level_of_training',
            field=models.CharField(blank=True, choices=[('VILLAGE', 'Village'), ('SHG', 'SHG'), ('CLF', 'CLF'), ('BLOCK', 'Block'), ('BLOCK_DISTRICT', 'Block/District'), ('CMTC/BLOCK', 'CMTC/Block'), ('DISTRICT', 'District'), ('STATE', 'State'), ('WITHIN_STATE', 'Within State'), ('OUTSIDE_STATE', 'Outside State')], max_length=32, null=True, verbose_name='Level of training'),
        ),
    ]
