# Generated by Django 5.2.6 on 2025-09-27 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0005_alter_trainingplan_level_of_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('district_code', models.CharField(blank=True, max_length=50, null=True)),
                ('state_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('district_name_en', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('district_short_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('district_name_local', models.CharField(blank=True, max_length=255, null=True)),
                ('lgd_code', models.CharField(blank=True, max_length=64, null=True)),
                ('language_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'indexes': [models.Index(fields=['state_id'], name='bmmu_distri_state_i_1e86ad_idx'), models.Index(fields=['district_name_en'], name='bmmu_distri_distric_720c86_idx')],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('block_code', models.CharField(blank=True, max_length=64, null=True)),
                ('block_name_en', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('block_name_local', models.CharField(blank=True, max_length=255, null=True)),
                ('rural_urban_area', models.CharField(blank=True, max_length=5, null=True)),
                ('lgd_code', models.CharField(blank=True, max_length=64, null=True)),
                ('language_id', models.CharField(blank=True, max_length=20, null=True)),
                ('state_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('district_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='bmmu.district')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
            },
        ),
        migrations.CreateModel(
            name='Panchayat',
            fields=[
                ('panchayat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('panchayat_code', models.CharField(blank=True, max_length=64, null=True)),
                ('panchayat_name_en', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('panchayat_name_local', models.CharField(blank=True, max_length=255, null=True)),
                ('rural_urban_area', models.CharField(blank=True, max_length=5, null=True)),
                ('language_id', models.CharField(blank=True, max_length=20, null=True)),
                ('lgd_code', models.CharField(blank=True, max_length=64, null=True)),
                ('state_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panchayats', to='bmmu.block')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panchayats', to='bmmu.district')),
            ],
            options={
                'verbose_name': 'Panchayat',
                'verbose_name_plural': 'Panchayats',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('village_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('village_code', models.CharField(blank=True, max_length=128, null=True)),
                ('village_name_english', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('village_name_local', models.CharField(blank=True, max_length=255, null=True)),
                ('rural_urban_area', models.CharField(blank=True, max_length=5, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('lgd_code', models.CharField(blank=True, max_length=64, null=True)),
                ('state_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('district_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('block_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='bmmu.panchayat')),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
            },
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['district'], name='bmmu_block_distric_dfd8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['block_name_en'], name='bmmu_block_block_n_262066_idx'),
        ),
        migrations.AddIndex(
            model_name='panchayat',
            index=models.Index(fields=['district', 'block'], name='bmmu_pancha_distric_17bc5c_idx'),
        ),
        migrations.AddIndex(
            model_name='panchayat',
            index=models.Index(fields=['panchayat_name_en'], name='bmmu_pancha_panchay_139fed_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['panchayat'], name='bmmu_villag_panchay_89b704_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['village_name_english'], name='bmmu_villag_village_9f9aa4_idx'),
        ),
    ]
