# Generated by Django 5.2.6 on 2025-09-27 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0006_district_block_panchayat_village_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_aspirational',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='Mandal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Mandal',
                'verbose_name_plural': 'Mandals',
                'indexes': [models.Index(fields=['name'], name='bmmu_mandal_name_f5c67c_idx')],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='mandal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='bmmu.mandal'),
        ),
        migrations.CreateModel(
            name='DistrictCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_index=True, max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='bmmu.district')),
            ],
            options={
                'verbose_name': 'District Category',
                'verbose_name_plural': 'District Categories',
                'indexes': [models.Index(fields=['district'], name='bmmu_distri_distric_3e104f_idx'), models.Index(fields=['category_name'], name='bmmu_distri_categor_4acbd7_idx')],
                'unique_together': {('district', 'category_name')},
            },
        ),
    ]
