# Generated by Django 5.2.6 on 2025-09-29 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0007_block_is_aspirational_mandal_district_mandal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmmuBlockAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmmu_user_assignments', to='bmmu.block')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bmmu_block_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BMMU Block Assignment',
                'verbose_name_plural': 'BMMU Block Assignments',
                'unique_together': {('user', 'block')},
            },
        ),
        migrations.CreateModel(
            name='DmmuDistrictAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmmu_user_assignments', to='bmmu.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dmmu_district_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DMMU District Assignment',
                'verbose_name_plural': 'DMMU District Assignments',
                'unique_together': {('user', 'district')},
            },
        ),
    ]
