# Generated by Django 5.2.6 on 2025-09-29 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0008_bmmublockassignment_dmmudistrictassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_block', to='bmmu.block'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_district', to='bmmu.district'),
        ),
    ]
