# Generated by Django 5.2.6 on 2025-09-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0009_alter_beneficiary_block_alter_beneficiary_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='aadhaar_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Aadhaar No'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='ebk_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='eBK ID'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='nrega_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NREGA Job Card No'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='nrlm_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NRLM MIS ID'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='pmay_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PMAY-G ID'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='secc_tin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SECC TIN'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='state_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='STATE MIS ID'),
        ),
    ]
