# Generated by Django 5.2.6 on 2025-09-29 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0010_alter_beneficiary_aadhaar_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('shg_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='SHG Code')),
                ('shg_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='SHG Name')),
                ('date_of_formation', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shgs', to='bmmu.block')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shgs', to='bmmu.district')),
            ],
            options={
                'verbose_name': 'SHG',
                'verbose_name_plural': 'SHGs',
                'ordering': ['shg_code'],
                'indexes': [models.Index(fields=['shg_code'], name='bmmu_shg_shg_cod_9426f6_idx'), models.Index(fields=['state'], name='bmmu_shg_state_b932a2_idx')],
            },
        ),
    ]
