# Generated by Django 5.2.6 on 2025-10-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0012_trainerbatchregistration_trainingpartnercentre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingPartnerAssignment',
        ),
    ]
