# Generated by Django 5.2.6 on 2025-10-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0013_delete_trainingpartnerassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrequest',
            name='code',
        ),
    ]
