# Generated by Django 5.2.6 on 2025-10-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0015_batch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchBeneficiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_beneficiaries', to='bmmu.batch')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefs_batch_participation', to='bmmu.beneficiary')),
            ],
            options={
                'verbose_name': 'Beneficiary Batch Participation',
                'verbose_name_plural': 'Beneficiary Batch Participation',
                'unique_together': {('beneficiary', 'batch')},
            },
        ),
    ]
