# Generated by Django 5.2.6 on 2025-10-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0016_batchbeneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertrainer',
            name='designation',
            field=models.CharField(blank=True, choices=[('BRP', 'BRP'), ('DRP', 'DRP'), ('SRP', 'SRP')], db_index=True, max_length=3, null=True, verbose_name='Designation'),
        ),
    ]
