# Generated by Django 5.2.6 on 2025-10-07 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0017_alter_mastertrainer_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ONGOING', 'Ongoing'), ('UPCOMING', 'UPCOMING'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='BatchAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('csv_upload', models.FileField(blank=True, null=True, upload_to='attendance_csvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='bmmu.batch')),
            ],
            options={
                'verbose_name': 'Batch Attendance',
                'verbose_name_plural': 'Batch Attendances',
                'unique_together': {('batch', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ParticipantAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.PositiveIntegerField()),
                ('participant_name', models.CharField(max_length=200)),
                ('participant_role', models.CharField(choices=[('trainer', 'Trainer'), ('beneficiary', 'Beneficiary')], max_length=50)),
                ('present', models.BooleanField(default=False)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_records', to='bmmu.batchattendance')),
            ],
        ),
        migrations.CreateModel(
            name='BatchEkycVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.PositiveIntegerField()),
                ('participant_role', models.CharField(choices=[('trainer', 'Trainer'), ('beneficiary', 'Beneficiary')], max_length=20)),
                ('ekyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('ekyc_document', models.FileField(blank=True, null=True, upload_to='ekyc_documents/')),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekyc_verifications', to='bmmu.batch')),
            ],
            options={
                'verbose_name': 'Batch eKYC Verification',
                'verbose_name_plural': 'Batch eKYC Verifications',
                'unique_together': {('batch', 'participant_id', 'participant_role')},
            },
        ),
    ]
