# Generated by Django 5.2.6 on 2025-10-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0018_alter_batch_status_batchattendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ONGOING', 'Ongoing'), ('SCHEDULED', 'SCHEDULED'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
