# Generated by Django 5.2.6 on 2025-10-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0020_alter_trainingrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='status',
            field=models.CharField(choices=[('BATCHING', 'Batching Phase'), ('PENDING', 'Pending Approval'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='BATCHING', max_length=20),
        ),
    ]
