# Generated by Django 5.2.6 on 2025-10-10 19:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0021_alter_trainingrequest_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingplanpartner',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trainingplanpartner',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='trainingplanpartner',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='trainingplanpartner',
            name='training_plan',
        ),
        migrations.RemoveField(
            model_name='trainingpartnerbatch',
            name='drp_payment_actual',
        ),
        migrations.RemoveField(
            model_name='trainingpartnerbatch',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='trainingpartnertargets',
            name='evidence_file',
        ),
        migrations.RemoveField(
            model_name='trainingpartnertargets',
            name='target_key',
        ),
        migrations.AddField(
            model_name='trainingpartnertargets',
            name='allocated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trainingpartnertargets',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tp_district_targets', to='bmmu.district'),
        ),
        migrations.AddField(
            model_name='trainingpartnertargets',
            name='financial_year',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Financial year'),
        ),
        migrations.AddField(
            model_name='trainingpartnertargets',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainingpartnertargets',
            name='training_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_targets', to='bmmu.trainingplan'),
        ),
        migrations.AlterField(
            model_name='trainingpartnerbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ONGOING', 'Ongoing'), ('SCHEDULED', 'SCHEDULED'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingpartnertargets',
            name='target_count',
            field=models.PositiveIntegerField(verbose_name='Target count (batches)'),
        ),
        migrations.AddIndex(
            model_name='trainingpartnertargets',
            index=models.Index(fields=['financial_year'], name='bmmu_traini_financi_b9dd7d_idx'),
        ),
        migrations.DeleteModel(
            name='TrainingPlanPartner',
        ),
    ]
