# Generated by Django 5.2.6 on 2025-10-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0022_alter_trainingplanpartner_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingpartnertargets',
            name='target_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Target count (batches)'),
        ),
    ]
