# Generated by Django 5.2.6 on 2025-10-11 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0023_alter_trainingpartnertargets_target_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertrainer',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_block', to='bmmu.block'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_district', to='bmmu.district'),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='gram_panchayat',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='village',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
