# Generated by Django 5.2.6 on 2025-10-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0024_mastertrainer_block_mastertrainer_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertrainer',
            name='gram_panchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_gp', to='bmmu.panchayat'),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_village', to='bmmu.village'),
        ),
    ]
