# Generated by Django 5.2.6 on 2025-10-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0025_alter_mastertrainer_gram_panchayat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertrainer',
            name='training_plan',
            field=models.ForeignKey(blank=True, help_text='Reference TrainingPlan used as canonical theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_trainers', to='bmmu.trainingplan'),
        ),
    ]
