# Generated by Django 5.2.6 on 2025-10-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmmu', '0026_mastertrainer_training_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastertrainer',
            name='training_plan',
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='theme',
            field=models.CharField(blank=True, choices=[('Farm LH', 'Farm LH'), ('FNHW', 'FNHW'), ('M&E', 'M&E'), ('MCLF', 'MCLF'), ('MF&FI', 'MF&FI'), ('Non Farm', 'Non Farm'), ('NONFARM LH', 'NONFARM LH'), ('SISD', 'SISD'), ('SMCB', 'SMCB'), ('TNCB', 'TNCB'), ('Fishery', 'Fishery')], db_index=True, help_text="Canonical theme mapped from CSV 'theme' column", max_length=50, null=True, verbose_name='Theme'),
        ),
    ]
